from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'quizzes',
    'quiz_result',
    'user_progress',
    'bookmark_quiz',
    'DebateSession',
    'Message',
    'companion_create',
    'Interaction',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'quiz_data_result': 'quiz_result',
        'user_progress_report': 'user_progress',
        'bookmark': 'bookmark_quiz',
        'debatePoint': 'DebateSession',
        'companionData': 'companion_create',
    },
    'quizzes': {
    },
    'quiz_result': {
        'user': 'User',
    },
    'user_progress': {
        'user': 'User',
    },
    'bookmark_quiz': {
        'user': 'User',
    },
    'DebateSession': {
        'user': 'User',
        'messages': 'Message',
    },
    'Message': {
        'session': 'DebateSession',
    },
    'companion_create': {
        'interactions': 'Interaction',
        'user': 'User',
    },
    'Interaction': {
        'companion': 'companion_create',
    },
}

# fmt: on