# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


from typing_extensions import LiteralString
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class Basequizzes(_PrismaModel):
    __prisma_model__: ClassVar[Literal['quizzes']] = 'quizzes'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.quizzesActions[_PrismaModelT]':
        from .client import get_client

        return actions.quizzesActions[_PrismaModelT](client or get_client(), cls)


class Basequiz_result(_PrismaModel):
    __prisma_model__: ClassVar[Literal['quiz_result']] = 'quiz_result'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.quiz_resultActions[_PrismaModelT]':
        from .client import get_client

        return actions.quiz_resultActions[_PrismaModelT](client or get_client(), cls)


class Baseuser_progress(_PrismaModel):
    __prisma_model__: ClassVar[Literal['user_progress']] = 'user_progress'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.user_progressActions[_PrismaModelT]':
        from .client import get_client

        return actions.user_progressActions[_PrismaModelT](client or get_client(), cls)


class Basebookmark_quiz(_PrismaModel):
    __prisma_model__: ClassVar[Literal['bookmark_quiz']] = 'bookmark_quiz'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.bookmark_quizActions[_PrismaModelT]':
        from .client import get_client

        return actions.bookmark_quizActions[_PrismaModelT](client or get_client(), cls)


class BaseDebateSession(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DebateSession']] = 'DebateSession'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DebateSessionActions[_PrismaModelT]':
        from .client import get_client

        return actions.DebateSessionActions[_PrismaModelT](client or get_client(), cls)


class BaseMessage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Message']] = 'Message'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MessageActions[_PrismaModelT]':
        from .client import get_client

        return actions.MessageActions[_PrismaModelT](client or get_client(), cls)


class Basecompanion_create(_PrismaModel):
    __prisma_model__: ClassVar[Literal['companion_create']] = 'companion_create'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.companion_createActions[_PrismaModelT]':
        from .client import get_client

        return actions.companion_createActions[_PrismaModelT](client or get_client(), cls)


class BaseInteraction(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Interaction']] = 'Interaction'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.InteractionActions[_PrismaModelT]':
        from .client import get_client

        return actions.InteractionActions[_PrismaModelT](client or get_client(), cls)


